name: StarAnimatedMenu
main: ru.entryset.main.Main
version: 3.2
api-version: 1.13
softdepend: [PlaceholderAPI, Vault, PlayerPoints, DKCoins]
commands:
  staranimatedmenu:
    aliases: [sam, staram, staranimatedm, samenu, smenu]